if (${CMAKE_SYSTEM_NAME} MATCHES Windows)
    set(USER_CONFIG_DIR $ENV{APPDATA})
else()
    if ($ENV{XDG_CONFIG_HOME})
        set(USER_CONFIG_DIR $ENV{XDG_CONFIG_HOME})
    else()
        set(USER_CONFIG_DIR $ENV{HOME}/.config)
    endif()
endif()
